version: 0.0
os: linux	
files:	
  - source: /docker-compose.yml
    destination: /home/ubuntu/deploy	    
hooks:	
  AfterInstall:
    - location: scripts/check_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root      
