version: 0.2

phases:
  pre_build:
    commands:
      - echo ================Logging in to Amazon ECR================
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q8s1o0x0
  build:
    commands:
      - echo ================Build Maven Package and Docker Image================
      - mvn clean package
      - docker build -t sig-devsecops-ib-ecr:1.0 .
      - docker save -o sig-devsecops-ib-ecr-1-0.tar sig-devsecops-ib-ecr:1.0
      - docker tag sig-devsecops-ib-ecr:1.0 public.ecr.aws/q8s1o0x0/sig-devsecops-ib-ecr:1.0
  post_build:
    commands:
      - echo ================Build completed on `date`================
      - echo ================Pushing the Docker image================
      - docker push public.ecr.aws/q8s1o0x0/sig-devsecops-ib-ecr:1.0
artifacts:
  files:
     - aws_stack.yml
     - docker-compose.yml
     - appspec.yml
     - scripts/start_server
     - scripts/stop_server