version: "3.2"
services:
#APP*****************************************
  insecurebank:
    image: insecurebank:1.0
    container_name: insecurebank
    volumes:
      - $HOME/data/insecurebank-logs:/opt/logs/
    expose:
      - 80
    ports:
      - 80:8080
    networks:
      - insecurebank
    user: ${CURRENT_UID}
    restart: always

#########NETWORKS##########
networks:
  insecurebank:
